### ISSUE TITLE
radomly and dupplicate 

### ISSUE THREAD

**Issue by asdfxD** [johnoclockdk/cs2_Advertisements_Database#21]
since last update, my chat adverts are posted randomly or sometimes the same message twice or three times after 60 seconds.

**Comment by johnoclockdk** [comment]
@asdfxD have you restart the server as the timer is naver unloaded on update or upload

**Comment by asdfxD** [comment]
i restartet the server for test, no dupplicate message until now but they are randomly. not from ID 1-9.

**Comment by johnoclockdk** [comment]
could you show me the context of database

**Comment by johnoclockdk** [comment]
im closing this
