### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by IG-PhantomX** [johnoclockdk/cs2_Advertisements_Database#30]
I have installed the plugin successfully, but how do we actually use it?  Are there in game commands?  Do we have to edit it manually in the SQL db?

**Comment by johnoclockdk** [comment]
you can manually insert them in a db or use the commands 
[1173452786562781276](https://discord.com/channels/1160907911501991946/1173452786562781276)

**Comment by johnoclockdk** [comment]
issue fixed
