### ISSUE TITLE
Adding new features2 )

### ISSUE THREAD

**Issue by suspectykt** [johnoclockdk/cs2_Advertisements_Database#6]
Hello, I suggest you make it the value of distinguishing servers
Let's say there are 3 servers, awp, retake and dm
awp adv id 1
retake adv id 2
dm adv id 3
and it will be possible to write different text for different servers

Example:
The /gun menu is available on RETAKE, there is no AWP and you need to add information to the advertisement that there is a /gun menu available on the retake server but not for AWP

Then it will be possible to use one database and divide it into servers where to display this advertising

Example
adv test chat
show this advertisement on servers with ID [1], [2], [3]
adv test2 chat show on servers [1], [3]

**Comment by johnoclockdk** [comment]
thanks for raise this on git and it been work on com back later to see i have added it
